# Lab 11: Monday, June 14

[Course evaluations](https://evals.mcmaster.ca/login.php) opened today, and close Friday, June 18.

Reminder that today is the last lab. 
In particular, there will be no lab on Wednesday before the exam.

Today's lab is general review.

## Questions?

## Missing Number

Write a function whose parameter is a list which is supposed to contain a range of numbers, except one of the numbers is missing.
For instance, `[1, 2, 4, 5]` or `[1, 2, 3, 4, 5, 6, 7, 9, 10]`. 

Write a function `missing_number` which returns the missing number from such a list.
You can assume that the list will always start at `1` and that the endpoints (1 and the maximum) are always included.
If there's no number missing, return `None`.

Do this two ways: once using a loop and once using sets.

In [1]:
def missing_number_loop(nums):
    # using a for loop
    
    for i in range(1, nums[-1]+1):
        if nums[i-1] != i:
            return i

In [2]:
print(missing_number_loop([1,2,4,5]))  # 3
print(missing_number_loop([1,2,3,4,5,6,7,9,10]))  # 8
print(missing_number_loop([1,2,3,4,5]))  # None

3
8
None


In [3]:
def missing_number_sets(nums):
    # using sets
    
    # create a set of all the numbers in the full range
    all_nums = set([i for i in range(1, nums[-1]+1)])
    our_nums = set(nums)
    
    missing = all_nums.difference(our_nums)
    
    if missing == set():
        return None
    else:
        return int(missing.pop())

In [4]:
print(missing_number_sets([1,2,4,5]))  # 3
print(missing_number_sets([1,2,3,4,5,6,7,9,10]))  # 8
print(missing_number_sets([1,2,3,4,5]))  # None

3
8
None


## Clock

Write a function which converts between different methods of telling time.
Its input should be a string such as `'quarter to twelve'` or `'half past one'`, and you should return `'11:45'` or `'1:30'`, respectively.

The input will be of the form `[interval] [to/past] [hour]`, unless the time is on the hour, in which case the input will be of the form `"[hour] o'clock"`.
You may assume that the time will always be a multiple of five.

You may assume that the input will be as you'd expect (the input won't be `'thirty-five past one'`, it would be `'twenty-five to two'`) and that all times will be on a twelve-hour clock (no 14:00, etc).

In [5]:
def clock(time):
    intervals = {
        'five': 5,
        'ten': 10,
        'quarter': 15,
        'twenty': 20,
        'twenty-five': 25,
        'half': 30
    }
    
    hours = {
        'one': 1,
        'two': 2,
        'three': 3,
        'four': 4,
        'five': 5,
        'six': 6,
        'seven': 7,
        'eight': 8,
        'nine': 9,
        'ten': 10,
        'eleven': 11,
        'twleve': 12
    }
    
    if "o'clock" in time:  # then we're on the hour
        hour, interval = time.split()
        return str(hours[hour]) + ':00'
    
    interval, to_past, hour = time.split()
    
    if to_past == 'past':
        num_hour = hours[hour]
        minutes = intervals[interval]
    
    else:  # to_past == 'to'
        num_hour = hours[hour] - 1
        minutes = 60 - intervals[interval]
        
    if num_hour == 0:  # because 1-1 = 0 from two lines ago
        num_hour = 12
    
    output = str(num_hour) + ':' + str(minutes)
    return output

In [6]:
print(clock('twenty-five past two'))  # 2:25
print(clock("eleven o'clock"))  # 11:00
print(clock('quarter to one'))  # 12:45

2:25
11:00
12:45


## Creating a Matrix

This is Prof. Lovric's question 116.

Write a function `eye_modified(n,a,b)` which returns an $n \times n$ matrix $M$ whose entries are given by $$M_{ij} = \begin{cases} a & i=j, \\ b & i\neq j. \end{cases}$$

Do this once using lists and once using numpy arrays/matrices.

In [7]:
def eye_modified_lists(n, a, b):
    M = []
    
    for i in range(n):
        this_row = []
        
        for j in range(n):
            if i == j:
                this_entry = a
            else:
                this_entry = b
            this_row.append(this_entry)
        
        M.append(this_row)
        
    return M

In [8]:
print(eye_modified_lists(3,1,0))  # [[1,0,0], [0,1,0], [0,0,1]]
print(eye_modified_lists(5,11,1))  # [[11, 1, 1, 1, 1], [1, 11, 1, 1, 1], [1, 1, 11, 1, 1], [1, 1, 1, 11, 1], [1, 1, 1, 1, 11]]
print(eye_modified_lists(2,0,1))  # [[0,1], [1,0]]

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]
[[11, 1, 1, 1, 1], [1, 11, 1, 1, 1], [1, 1, 11, 1, 1], [1, 1, 1, 11, 1], [1, 1, 1, 1, 11]]
[[0, 1], [1, 0]]


In [9]:
def eye_modified_list_comp(n, a, b):
    return [[a if i==j else b for j in range(n)] for i in range(n)]

In [10]:
print(eye_modified_list_comp(3,1,0))  # [[1,0,0], [0,1,0], [0,0,1]]
print(eye_modified_list_comp(5,11,1))  # [[11, 1, 1, 1, 1], [1, 11, 1, 1, 1], [1, 1, 11, 1, 1], [1, 1, 1, 11, 1], [1, 1, 1, 1, 11]]
print(eye_modified_list_comp(2,0,1))  # [[0,1], [1,0]]

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]
[[11, 1, 1, 1, 1], [1, 11, 1, 1, 1], [1, 1, 11, 1, 1], [1, 1, 1, 11, 1], [1, 1, 1, 1, 11]]
[[0, 1], [1, 0]]


In [11]:
import numpy as np

def eye_modified_numpy(n, a, b):
    M_diag = np.diag((a-b) * np.ones(n))  # i==j on the diagonal
    # need to subtrace b to compensate for:
    B_matrix = b * np.ones((n,n))
    return M_diag + B_matrix

In [12]:
print(eye_modified_numpy(3,1,0))
print(eye_modified_numpy(5,11,1))
print(eye_modified_numpy(2,0,1))  # same expected output as above

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[11.  1.  1.  1.  1.]
 [ 1. 11.  1.  1.  1.]
 [ 1.  1. 11.  1.  1.]
 [ 1.  1.  1. 11.  1.]
 [ 1.  1.  1.  1. 11.]]
[[0. 1.]
 [1. 0.]]


## Magic Squares

A **magic square** is an $n \times n$ matrix whose row sums, column sums, and diagonal sums are all equal.
(The diagonal sums are the sums of both the main diagonal, and the **anti-diagonal**, going from the top-right to bottom-left.)

Write a function which returns `True` if the given matrix is a magic square, and `False` otherwise.
The matrices will be square numpy matrices.

In [13]:
import numpy as np

def is_magic_square(matrix):
    magic_sum = np.sum(np.diag(matrix))  # set the potential sum to the sum of the main diagonal
    
    for i in range(len(matrix)):
        row_sum = np.sum(matrix[i])  # checks the row
        col_sum = np.sum(matrix[:,i])  # checks the column
        
        if not (magic_sum == row_sum == col_sum):
            return False
        
    # we've checked that the sum of the main diagonal is equal
    # to the sum of all the rows and columns
    # it remains to check the anti-diagonal now
    # np.flipud "flips" the matrix top-to-bottom
    
    anti_diag = np.diag(np.flipud(matrix))
    
    return magic_sum == np.sum(anti_diag)

In [14]:
print(is_magic_square(np.matrix([[2,7,6],[9,5,1],[4,3,8]])))  # True
print(is_magic_square(np.matrix([[29**2, 1, 47**2], [41**2, 37**2, 1], [23**2, 41**2, 29**2]])))  # False -- this is The Parker Square (theparkersquare.com)
print(is_magic_square(np.matrix([[4,9,2], [3,5,7], [8,1,6]])))  # True

True
False
True


## Diagonally Dominant

A matrix is **(strictly) diagonally dominant** if the absolute value of its diagonal entries are strictly greater than the sum of the absolute values of the non-diagonal entries in the corresponding row.
That is, if $$|a_{ii}| > \sum_{j=1}^n |a_{ij}|$$ for all rows $i$.
Write a function that returns `True` if a matrix (here, a list of lists) is strictly diagonally dominant, and `False` otherwise.

You may assume the matrices are square.

In [15]:
def is_diag_dominant(matrix):
    for i in range(len(matrix)):
        diagonal_entry = abs(matrix[i][i])
        non_diag_sum = sum([abs(a_ij) for a_ij in matrix[i]]) - diagonal_entry
        
        if not (diagonal_entry > non_diag_sum):
            return False
        
    return True

In [16]:
print(is_diag_dominant([[10,1,2,3],[0,11,2,3],[0,1,12,3],[0,1,2,13]]))  # True
print(is_diag_dominant([[4,2,2],[0,5,-2],[-1,-2,7]]))  # False
print(is_diag_dominant([[-3,-2,-1],[-1,3,-2],[2,1,3]]))  # False
print(is_diag_dominant([[-4,-2,-1],[-1,-4,-2],[2,1,-4]]))  # True

True
False
False
True


## FizzBuzz

Write a program which prints the output from the game *FizzBuzz*. 
The game goes like this: two players alternate counting numbers, "1, 2, 3, 4, 5, ...", except if the number is a multiple of 3, you instead say "Fizz", and if the number is a multiple of 5, you say "Buzz".
In the case that the number is a multiple of 3 and 5, you say "FizzBuzz".

For instance, the first 15 "rounds" of this game are "1, 2, Fizz, 4, Buzz, Fizz, 7, 8, 9, Buzz, 11, Fizz, 13, 14, FizzBuzz".

Write code which prints the first 100 "rounds" of a game of FizzBuzz.

In [17]:
# first attempt

for i in range(1, 101):
    if i % 3 == 0 and i % 5 == 0:
        print('FizzBuzz')
    elif i % 3 == 0:
        print('Fizz')
    elif i % 5 == 0:
        print('Buzz')
    else:
        print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


This code is _ok_ but it's not very modular.
Meaning, if we wanted to change the divisors $3$ and $5$ to something else, it would be tricky.
(Well, it wouldn't be _too_ tricky for this small example, but let's see if we can write something better, which will be easier to implement in the next part.)

In [18]:
# v2

for i in range(1,101):
    output = ''
    if i % 3 == 0:
        output += 'Fizz'
    if i % 5 == 0:
        output += 'Buzz'
    if output == '':
        output = i
    print(output)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


Now write a function `fizzbuzz(n, fb_dict)` which prints the first `n` rounds of FizzBuzz.
Except, instead of just considering 3 and 5, we're given `fb_dict`, a dictionary which maps numbers to strings.
In this dictionary you'll find things of the form `3: 'Fizz'`, `5: 'Buzz'`, or `7: 'Fuzz'`.

The idea is exactly the same as before: if the number is a multiple of exactly one of the keys in the dictionary, the corresponding value should be the output. 
But if the number is divisible by more than just one of the keys, the output should be the concatination of all the corresponding values.

You may assume that the keys in the dictionary are listed in increasing order.

In [19]:
def fizzbuzz(n, fb_dict):
    for i in range(1, n+1):
        output = ''
        
        for factor in fb_dict.keys():
            if i % factor == 0:
                output += fb_dict[factor]
            
        if output == '':
            output = i
            
        print(output)

In [20]:
fizzbuzz(100, {3: 'Fizz', 5: 'Buzz'})  # should print the same as before

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


In [21]:
fizzbuzz(10, {1: 'Fizz'})  # should print 'Fizz' 10 times

Fizz
Fizz
Fizz
Fizz
Fizz
Fizz
Fizz
Fizz
Fizz
Fizz


In [22]:
fizzbuzz(60, {2: 'Fizzy', 3: 'Fizz', 4: 'Buzzy', 5: 'Buzz'})

1
Fizzy
Fizz
FizzyBuzzy
Buzz
FizzyFizz
7
FizzyBuzzy
Fizz
FizzyBuzz
11
FizzyFizzBuzzy
13
Fizzy
FizzBuzz
FizzyBuzzy
17
FizzyFizz
19
FizzyBuzzyBuzz
Fizz
Fizzy
23
FizzyFizzBuzzy
Buzz
Fizzy
Fizz
FizzyBuzzy
29
FizzyFizzBuzz
31
FizzyBuzzy
Fizz
Fizzy
Buzz
FizzyFizzBuzzy
37
Fizzy
Fizz
FizzyBuzzyBuzz
41
FizzyFizz
43
FizzyBuzzy
FizzBuzz
Fizzy
47
FizzyFizzBuzzy
49
FizzyBuzz
Fizz
FizzyBuzzy
53
FizzyFizz
Buzz
FizzyBuzzy
Fizz
Fizzy
59
FizzyFizzBuzzyBuzz


Remember to fill out the [course evaluation](https://evals.mcmaster.ca)!
Good luck on the exam!